// gkc_hash_code : 01GV08E07716MKFVFKX31BQC9G
export const STEPS = {
  POLICY: 1,
  CONFIRM_NUMBER: 2,
  INPUT: 3,
  CONFIRM_INPUT: 4,
  PAY: 5,
};

export const REGEX_NUMBER = /^[0-9]+$/;

export const CARD_NUMBER_DUPLICATE = [
  '0000',
  '1111',
  '2222',
  '3333',
  '4444',
  '5555',
  '6666',
  '7777',
  '8888',
  '9999',
];

export const SWITCH = {
  JGW: 'jgw',
  CHANGE_DEVICE: 'device',
  DEVICE_1PAY: '1device1pay',
};

export const STATUS_CODE = {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

export const AUTHENTICATION_TYPE = {
  JALPAY_REGISTRATION: 'JALPAY_MEMBERSHIP_JOIN',
  JGW: 'JGW_SWITCH_SMS',
  CHANGE_DEVICE: 'CHANGE_DEVICE',
  DEVICE_1PAY: 'DEVICE_AUTHENTICATION',
};

export const JALPAY_REGIS_STATUS = {
  UNCHECKED: 'UNCHECKED',
  HOLD: 'HOLD',
  REJECTED: 'REJECTED',
};

export const OPTION_PROFESSTION = [
  { value: 'EXECUTIVE', label: '会社役員' },
  { value: 'EMPLOYEE_MANAGER', label: '会社員（管理職）' },
  { value: 'EMPLOYEE_GENERAL', label: '会社員（一般職）' },
  { value: 'CIVIL_SERVANT', label: '公務員' },
  { value: 'TEACHER', label: '教職員' },
  { value: 'EMPLOYEE_ORGANIZATION', label: '団体職員' },
  { value: 'DOCTOR', label: '医師' },
  { value: 'DENTAL_DOCTOR', label: '歯科医師' },
  {
    value: 'LAWYERS_ACCOUNTANTS_TAX_ACCOUNTANTS',
    label: '弁護士・会計士・税理士',
  },
  { value: 'JUDICIAL_ADMINISTRATIVE_SCRIVENER', label: '司法書士・行政書士等' },
  { value: 'SELF_EMPLOYED', label: '自営業' },
  { value: 'CONTRACT_EMPLOYEE', label: '契約社員' },
  { value: 'TEMPORARY_EMPLOYEE', label: '嘱託' },
  { value: 'PART_TIMER', label: 'パート・アルバイト' },
  { value: 'HOUSE_WIFE', label: '主婦' },
  { value: 'STUDENT', label: '学生' },
  { value: 'RETIREMENT', label: '退職者' },
  { value: 'DISEMPLOYMENT', label: '無職' },
  { value: 'OTHER', label: 'その他' },
];

export const OPTION_DESTINATION = [
  { value: 'USA', label: 'アメリカ合衆国' },
  { value: 'KOREA', label: '韓国' },
  { value: 'CHINA', label: '中国' },
  { value: 'TAIWAN', label: '台湾' },
  { value: 'THAILAND', label: 'タイ' },
  { value: 'HONG_KONG', label: '香港' },
  { value: 'ICELAND', label: 'アイスランド' },
  { value: 'IRELAND', label: 'アイルランド' },
  { value: 'AZERBAIJAN', label: 'アゼルバイジャン' },
  { value: 'AFGHANISTAN', label: 'アフガニスタン' },
  { value: 'VIRGIN_ISLANDS_US', label: 'アメリカ領ヴァージン諸島' },
  { value: 'AMERICAN_SAMOA', label: 'アメリカ領サモア' },
  { value: 'UNITED_ARAB_EMIRATES', label: 'アラブ首長国連邦' },
  { value: 'ALGERIA', label: 'アルジェリア' },
  { value: 'ARGENTINA', label: 'アルゼンチン' },
  { value: 'ARUBA', label: 'アルバ' },
  { value: 'ALBANIA', label: 'アルバニア' },
  { value: 'ARMENIA', label: 'アルメニア' },
  { value: 'ANGUILLA', label: 'アンギラ' },
  { value: 'ANGOLA', label: 'アンゴラ' },
  { value: 'ANTIGUA_AND_BARBUDA', label: 'アンティグア・バーブーダ' },
  { value: 'ANDORRA', label: 'アンドラ' },
  { value: 'YEMEN', label: 'イエメン' },
  { value: 'UNITED_KINGDOM', label: 'イギリス' },
  { value: 'BRITISH_INDIAN_OCEAN_TERRITORY', label: 'イギリス領インド洋地域' },
  { value: 'VIRGIN_ISLANDS_BRITISH', label: 'イギリス領ヴァージン諸島' },
  { value: 'ISRAEL', label: 'イスラエル' },
  { value: 'ITALY', label: 'イタリア' },
  { value: 'IRAQ', label: 'イラク' },
  { value: 'INDIA', label: 'インド' },
  { value: 'INDONESIA', label: 'インドネシア' },
  { value: 'WALLIS_AND_FUTUNA', label: 'ウォリス・フツナ' },
  { value: 'UGANDA', label: 'ウガンダ' },
  { value: 'UKRAINE', label: 'ウクライナ' },
  { value: 'UZBEKISTAN', label: 'ウズベキスタン' },
  { value: 'URUGUAY', label: 'ウルグアイ' },
  { value: 'ECUADOR', label: 'エクアドル' },
  { value: 'EGYPT', label: 'エジプト' },
  { value: 'ESTONIA', label: 'エストニア' },
  { value: 'ETHIOPIA', label: 'エチオピア' },
  { value: 'ERITREA', label: 'エリトリア' },
  { value: 'EL_SALVADOR', label: 'エルサルバドル' },
  { value: 'AUSTRALIA', label: 'オーストラリア' },
  { value: 'AUSTRIA', label: 'オーストリア' },
  { value: 'ALAND_ISLANDS', label: 'オーランド諸島' },
  { value: 'OMAN', label: 'オマーン' },
  { value: 'NETHERLANDS_ANTILLES', label: 'オランダ' },
  { value: 'GHANA', label: 'ガーナ' },
  { value: 'CAPE_VERDE', label: 'カーボベルデ' },
  { value: 'BAILIWICK_OF_GUERNSEY', label: 'ガーンジー' },
  { value: 'GUYANA', label: 'ガイアナ' },
  { value: 'KAZAKHSTAN', label: 'カザフスタン' },
  { value: 'QATAR', label: 'カタール' },
  { value: 'UNITED_STATES_MINOR_OUTLYING_ISLANDS', label: '合衆国領有小離島' },
  { value: 'CANADA', label: 'カナダ' },
  { value: 'GABON', label: 'ガボン' },
  { value: 'CAMEROON', label: 'カメルーン' },
  { value: 'GAMBIA', label: 'ガンビア' },
  { value: 'CAMBODIA', label: 'カンボジア' },
  { value: 'NORTHERN_MARIANA_ISLANDS', label: '北マリアナ諸島' },
  { value: 'GUINEA', label: 'ギニア' },
  { value: 'GUINEA_BISSAU', label: 'ギニアビサウ' },
  { value: 'CYPRUS', label: 'キプロス' },
  { value: 'CUBA', label: 'キューバ' },
  { value: 'CURACAO', label: 'キュラソー' },
  { value: 'GREECE', label: 'ギリシャ' },
  { value: 'KIRIBATI', label: 'キリバス' },
  { value: 'KYRGYZSTAN', label: 'キルギス' },
  { value: 'GUATEMALA', label: 'グアテマラ' },
  { value: 'GUADELOUPE', label: 'グアドループ' },
  { value: 'GUAM', label: 'グアム' },
  { value: 'KUWAIT', label: 'クウェート' },
  { value: 'COOK_ISLANDS', label: 'クック諸島' },
  { value: 'GREENLAND', label: 'グリーンランド' },
  { value: 'CHRISTMAS_ISLAND', label: 'クリスマス島' },
  { value: 'GRENADA', label: 'グレナダ' },
  { value: 'CROATIA', label: 'クロアチア' },
  { value: 'CAYMAN_ISLANDS', label: 'ケイマン諸島' },
  { value: 'KENYA', label: 'ケニア' },
  { value: 'COTE_DIVOIRE', label: 'コートジボワール' },
  { value: 'COCOS_ISLANDS', label: 'ココス（キーリング）諸島' },
  { value: 'COSTA_RICA', label: 'コスタリカ' },
  { value: 'COMOROS', label: 'コモロ' },
  { value: 'COLOMBIA', label: 'コロンビア' },
  { value: 'REPUBLIC_OF_THE_CONGO', label: 'コンゴ共和国' },
  { value: 'DEMOCRATIC_REPUBLIC_OF_THE_CONGO', label: 'コンゴ民主共和国' },
  { value: 'SAUDI_ARABIA', label: 'サウジアラビア' },
  {
    value: 'SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS',
    label: 'サウスジョージア・サウスサンドウィッチ諸島',
  },
  { value: 'SAMOA', label: 'サモア' },
  { value: 'SAINT_BARTHELEMY', label: 'サントメ・プリンシペ' },
  { value: 'SAINT_MARTIN', label: 'サン・バルテルミー' },
  { value: 'SAO_TOME_AND_PRINCIPE', label: 'ザンビア' },
  { value: 'ZAMBIA', label: 'サンピエール島・ミクロン島' },
  { value: 'SAINT_PIERRE_AND_MIQUELON', label: 'サンマリノ' },
  { value: 'SAN_MARINO', label: 'サン・マルタン（フランス領）' },
  { value: 'SIERRA_LEONE', label: 'シエラレオネ' },
  { value: 'DJIBOUTI', label: 'ジブチ' },
  { value: 'GIBRALTAR', label: 'ジブラルタル' },
  { value: 'JERSEY', label: 'ジャージー' },
  { value: 'JAMAICA', label: 'ジャマイカ' },
  { value: 'GEORGIA', label: 'ジョージア' },
  { value: 'SYRIAN_ARAB_REPUBLIC', label: 'シリア・アラブ共和国' },
  { value: 'SINGAPORE', label: 'シンガポール' },
  { value: 'SINT_MAARTEN', label: 'シント・マールテン（オランダ領）' },
  { value: 'ZIMBABWE', label: 'ジンバブエ' },
  { value: 'SWITZERLAND', label: 'スイス' },
  { value: 'SVALBARD_AND_JAN_MAYEN', label: 'スウェーデン' },
  { value: 'SWEDEN', label: 'スーダン' },
  { value: 'SUDAN', label: 'スヴァールバル諸島およびヤンマイエン島' },
  { value: 'SPAIN', label: 'スペイン' },
  { value: 'SURINAME', label: 'スリナム' },
  { value: 'SRI_LANKA', label: 'スリランカ' },
  { value: 'SLOVAKIA', label: 'スロバキア' },
  { value: 'SLOVENIA', label: 'スロベニア' },
  { value: 'SWAZILAND', label: 'スワジランド' },
  { value: 'SEYCHELLES', label: 'セーシェル' },
  { value: 'EQUATORIAL_GUINEA', label: '赤道ギニア' },
  { value: 'SENEGAL', label: 'セネガル' },
  { value: 'SERBIA', label: 'セルビア' },
  { value: 'SAINT_KITTS_AND_NEVIS', label: 'セントクリストファー・ネイビス' },
  {
    value: 'SAINT_VINCENT_AND_THE_GRENADINES',
    label: 'セントビンセントおよびグレナディーン諸島',
  },
  {
    value: 'SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA',
    label: 'セントヘレナ・アセンションおよびトリスタンダクーニャ',
  },
  { value: 'SAINT_LUCIA', label: 'セントルシア' },
  { value: 'SOMALIA', label: 'ソマリア' },
  { value: 'SOLOMON_ISLANDS', label: 'ソロモン諸島' },
  { value: 'TURKS_AND_CAICOS_ISLANDS', label: 'タークス・カイコス諸島' },
  { value: 'TAJIKISTAN', label: 'タジキスタン' },
  { value: 'TANZANIA', label: 'タンザニア' },
  { value: 'CZECH_REPUBLIC', label: 'チェコ' },
  { value: 'CHAD', label: 'チャド' },
  { value: 'CENTRAL_AFRICAN_REPUBLIC', label: '中央アフリカ共和国' },
  { value: 'TUNISIA', label: 'チュニジア' },
  { value: 'CHILE', label: 'チリ' },
  { value: 'TUVALU', label: 'ツバル' },
  { value: 'DENMARK', label: 'デンマーク' },
  { value: 'GERMANY', label: 'ドイツ' },
  { value: 'TOGO', label: 'トーゴ' },
  { value: 'TOKELAU', label: 'トケラウ' },
  { value: 'DOMINICAN_REPUBLIC', label: 'ドミニカ共和国' },
  { value: 'DOMINICA', label: 'ドミニカ国' },
  { value: 'TRINIDAD_AND_TOBAGO', label: 'トリニダード・トバゴ' },
  { value: 'TURKMENISTAN', label: 'トルクメニスタン' },
  { value: 'TURKEY', label: 'トルコ' },
  { value: 'TONGA', label: 'トンガ' },
  { value: 'NIGERIA', label: 'ナイジェリア' },
  { value: 'NAURU', label: 'ナウル' },
  { value: 'NAMIBIA', label: 'ナミビア' },
  { value: 'ANTARCTICA', label: '南極' },
  { value: 'NIUE', label: 'ニウエ' },
  { value: 'NICARAGUA', label: 'ニカラグア' },
  { value: 'NIGER', label: 'ニジェール' },
  { value: 'WESTERN_SAHARA', label: '西サハラ' },
  { value: 'NEW_CALEDONIA', label: 'ニューカレドニア' },
  { value: 'NEW_ZEALAND', label: 'ニュージーランド' },
  { value: 'NEPAL', label: 'ネパール' },
  { value: 'NORFOLK_ISLAND', label: 'ノーフォーク島' },
  { value: 'NORWAY', label: 'ノルウェー' },
  {
    value: 'HEARD_ISLAND_AND_MCDONALD_ISLANDS',
    label: 'ハード島とマクドナルド諸島',
  },
  { value: 'BAHRAIN', label: 'バーレーン' },
  { value: 'HAITI', label: 'ハイチ' },
  { value: 'PAKISTAN', label: 'パキスタン' },
  { value: 'VATICAN_CITY_STATE', label: 'バチカン市国' },
  { value: 'PANAMA', label: 'パナマ' },
  { value: 'VANUATU', label: 'バヌアツ' },
  { value: 'BAHAMAS', label: 'バハマ' },
  { value: 'PAPUA_NEW_GUINEA', label: 'パプアニューギニア' },
  { value: 'BERMUDA', label: 'バミューダ' },
  { value: 'PALAU', label: 'パラオ' },
  { value: 'PARAGUAY', label: 'パラグアイ' },
  { value: 'BARBADOS', label: 'バルバドス' },
  { value: 'PALESTINE', label: 'パレスチナ' },
  { value: 'HUNGARY', label: 'ハンガリー' },
  { value: 'BANGLADESH', label: 'バングラデシュ' },
  { value: 'EAST_TIMOR', label: '東ティモール' },
  { value: 'PITCAIRN', label: 'ピトケアン' },
  { value: 'FIJI', label: 'フィジー' },
  { value: 'PHILIPPINES', label: 'フィリピン' },
  { value: 'FINLAND', label: 'フィンランド' },
  { value: 'BHUTAN', label: 'ブータン' },
  { value: 'BOUVET_ISLAND', label: 'ブーベ島' },
  { value: 'PUERTO_RICO', label: 'プエルトリコ' },
  { value: 'FAROE_ISLANDS', label: 'フェロー諸島' },
  { value: 'FALKLAND_ISLANDS', label: 'フォークランド（マルビナス）諸島' },
  { value: 'BRAZIL', label: 'ブラジル' },
  { value: 'FRANCE', label: 'フランス' },
  { value: 'FRENCH_GUIANA', label: 'フランス領ギアナ' },
  { value: 'FRENCH_POLYNESIA', label: 'フランス領ポリネシア' },
  { value: 'FRENCH_SOUTHERN_TERRITORIES', label: 'フランス領南方・南極地域' },
  { value: 'BULGARIA', label: 'ブルガリア' },
  { value: 'BURKINA_FASO', label: 'ブルキナファソ' },
  { value: 'BRUNEI_DARUSSALAM', label: 'ブルネイ・ダルサラーム' },
  { value: 'BURUNDI', label: 'ブルンジ' },
  { value: 'VIET_NAM', label: 'ベトナム' },
  { value: 'BENIN', label: 'ベナン' },
  { value: 'BOLIVARIAN_OF_VENEZUELA', label: 'ベネズエラ・ボリバル共和国' },
  { value: 'BELARUS', label: 'ベラルーシ' },
  { value: 'BELIZE', label: 'ベリーズ' },
  { value: 'PERU', label: 'ペルー' },
  { value: 'BELGIUM', label: 'ベルギー' },
  { value: 'POLAND', label: 'ポーランド' },
  { value: 'BOSNIA_AND_HERZEGOVINA', label: 'ボスニア・ヘルツェゴビナ' },
  { value: 'BOTSWANA', label: 'ボツワナ' },
  {
    value: 'BONAIRE_SAINT_EUSTATIUS_AND_SABA',
    label: 'ボネール、シント・ユースタティウスおよびサバ',
  },
  { value: 'BOLIVIA', label: 'ボリビア多民族国' },
  { value: 'PORTUGAL', label: 'ポルトガル' },
  { value: 'HONDURAS', label: 'ホンジュラス' },
  { value: 'MARSHALL_ISLANDS', label: 'マーシャル諸島' },
  { value: 'MACAU', label: 'マカオ' },
  { value: 'MACEDONIA', label: 'マケドニア旧ユーゴスラビア共和国' },
  { value: 'MADAGASCAR', label: 'マダガスカル' },
  { value: 'MAYOTTE', label: 'マヨット' },
  { value: 'MALAWI', label: 'マラウイ' },
  { value: 'MALI', label: 'マリ' },
  { value: 'MALTA', label: 'マルタ' },
  { value: 'MARTINIQUE', label: 'マルティニーク' },
  { value: 'MALAYSIA', label: 'マレーシア' },
  { value: 'ISLE_OF_MAN', label: 'マン島' },
  { value: 'MICRONESIA', label: 'ミクロネシア連邦' },
  { value: 'SOUTH_AFRICA', label: '南アフリカ' },
  { value: 'SOUTH_SUDAN', label: '南スーダン' },
  { value: 'MYANMAR', label: 'ミャンマー' },
  { value: 'MEXICO', label: 'メキシコ' },
  { value: 'MAURITIUS', label: 'モーリシャス' },
  { value: 'MAURITANIA', label: 'モーリタニア' },
  { value: 'MOZAMBIQUE', label: 'モザンビーク' },
  { value: 'MONACO', label: 'モナコ' },
  { value: 'MALDIVES', label: 'モルディブ' },
  { value: 'MOLDOVA', label: 'モルドバ共和国' },
  { value: 'MOROCCO', label: 'モロッコ' },
  { value: 'MONGOLIA', label: 'モンゴル' },
  { value: 'MONTENEGRO', label: 'モンテネグロ' },
  { value: 'MONTSERRAT', label: 'モントセラト' },
  { value: 'JORDAN', label: 'ヨルダン' },
  { value: 'LAOS', label: 'ラオス人民民主共和国' },
  { value: 'LATVIA', label: 'ラトビア' },
  { value: 'LITHUANIA', label: 'リトアニア' },
  { value: 'LIVIA', label: 'リビア' },
  { value: 'LIECHTENSTEIN', label: 'リヒテンシュタイン' },
  { value: 'LIBERIA', label: 'リベリア' },
  { value: 'ROMANIA', label: 'ルーマニア' },
  { value: 'LUXEMBOURG', label: 'ルクセンブルク' },
  { value: 'RWANDA', label: 'ルワンダ' },
  { value: 'LESOTHO', label: 'レソト' },
  { value: 'LEBANON', label: 'レバノン' },
  { value: 'REUNION', label: 'レユニオン' },
  { value: 'RUSSIAN_FEDERATION', label: 'ロシア連邦' },
];

export const OPTION_TRANSACTION_PURPOSES = [
  { value: 'SIGHTSEEING', label: '観光' },
  { value: 'EDUCATION', label: '海外留学' },
  { value: 'BUSINESS', label: '海外出張' },
  { value: 'SHOPPING', label: 'ショッピング' },
  { value: 'OTHER', label: 'その他の個人的な支払' },
];
