name: Github Action for jmb-app-web
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Build application
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.15.0'
    - name: Run CI
      run: |
        yarn install
        yarn lint
        yarn build
