name: Github Action test NodeJS CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.15.0'
    - name: Run Yarn 
      run: yarn
    - name: Run tests
      run: yarn test
